name: Blog post workflow
on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update with latest blog posts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install feedsnippet
      run: go install github.com/ikawaha/feedsnippet@latest

    - name: Update README.md
      run: feedsnippet -config feedsnippet.yml -file README.md
      
    - name: Commit file changes
      run: |
          git config --local user.email 'takaaki.inada@users.noreply.github.com'
          git config --local user.name 'Takaaki Inada'
          git add .
          git diff --quiet --cached || git commit -m "Update feed snippet"
          git push origin main
